dockerID: alunde
clusterDomain: cryptoassetssubledger.com
gateway: crypto-assets-subledger-aws-gateway.dev.svc.cluster.local
apiRuleGroup: gateway.kyma-project.io
apiRuleVersion: v1alpha1
apiRules: apirules
services:
  app:
    name: crypto-rates-app
    service:
      port: 5000
  srv:
    name: crypto-rates-srv
    image:
      repository: crypto-rates-srv
      tag: "latest"
      pullPolicy: Always
      imagePullSecretName: docker-config
      port: 5001
    service:
      port: 5001
  uaa:
    name: crypto-rates-uaa
    xsappname: crypto-rates
    bindingName: crypto-rates-uaa-binding
    bindingSecretName: crypto-rates-uaa-binding-secret
  registry:
    name: crypto-rates-registry
    bindingName: crypto-rates-registry-binding
    bindingSecretName: crypto-rates-registry-binding-secret
  role:
    name: crypto-rates-role
    bindingName: crypto-rates-role-binding
  dest:
    name: crypto-rates-dest
    bindingName: crypto-rates-dest-binding
    bindingSecretName: crypto-rates-dest-binding-secret
