apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.services.role.name }}
rules:
  - apiGroups:
      - gateway.kyma-project.io
    resources:
      - apirules
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list