kind: Secret
apiVersion: v1
metadata:
  name: letsencrypt-xgm75
  generateName: letsencrypt-
  namespace: dev
  uid: a131efde-c1ae-4d72-8f5f-35964a96f901
  resourceVersion: '37175194'
  creationTimestamp: '2022-11-02T21:01:25Z'
  ownerReferences:
    - apiVersion: v1alpha1
      kind: Issuer
      name: letsencrypt
      uid: b8b8101a-98d5-492d-aa86-d70c4338f207
  managedFields:
    - manager: cert-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-11-02T21:01:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:privateKey': {}
        'f:metadata':
          'f:generateName': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"b8b8101a-98d5-492d-aa86-d70c4338f207"}': {}
        'f:type': {}
data:
  privateKey: >-
    LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtBL0ZVMFBweGZvVTR0ZEhNRXo1Z1hCMHlERWJ3Rll2L2ZEclh2WXk4ZXZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFcnhyWFkwSDkwT3Zxd2Y2clpQVHA5eE1KV21kc0l6MlYxKzVudklNMUNKQkpORDEvdVNFUwpnOEVaQlhRQ0Y3V282amMxcmhOYlhlaE5KcEQ4ODlySkN3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
type: Opaque