apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  annotations:
    cert.gardener.cloud/not-after: '2023-01-15T14:23:20Z'
  creationTimestamp: '2022-10-11T15:11:39Z'
  generation: 2
  labels:
    app.kubernetes.io/name: letsencrypt-cert
    cert.gardener.cloud/hash: b164663fc17e3149112374eb12cdfc086549da195c2c9904490f1d4a
  managedFields:
    - apiVersion: cert.gardener.cloud/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/name': {}
        'f:spec':
          .: {}
          'f:commonName': {}
          'f:issuerRef':
            .: {}
            'f:name': {}
            'f:namespace': {}
          'f:renew': {}
      manager: Mozilla
      operation: Update
      time: '2022-10-11T15:11:39Z'
    - apiVersion: cert.gardener.cloud/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:cert.gardener.cloud/not-after': {}
          'f:labels':
            'f:cert.gardener.cloud/hash': {}
        'f:spec':
          'f:secretRef':
            .: {}
            'f:name': {}
            'f:namespace': {}
      manager: cert-controller-manager
      operation: Update
      time: '2022-10-19T21:39:18Z'
    - apiVersion: cert.gardener.cloud/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:commonName': {}
          'f:conditions': {}
          'f:expirationDate': {}
          'f:issuerRef':
            .: {}
            'f:cluster': {}
            'f:name': {}
            'f:namespace': {}
          'f:message': {}
          'f:observedGeneration': {}
          'f:state': {}
      manager: cert-controller-manager
      operation: Update
      subresource: status
      time: '2022-10-19T21:39:18Z'
  name: letsencrypt-cert
  namespace: istio-system
  resourceVersion: '29609132'
  uid: 93777414-eab4-4e98-968d-b251ad4f57fc
spec:
  commonName: '*.cryptoassetssubledger.com'
  issuerRef:
    name: letsencrypt
    namespace: dev
  renew: false
  secretRef:
    name: letsencrypt-cert-jx569
    namespace: istio-system
  csr: !<tag:yaml.org,2002:js/undefined> ''
  secretName: !<tag:yaml.org,2002:js/undefined> ''
status:
  commonName: '*.cryptoassetssubledger.com'
  conditions:
    - lastTransitionTime: '2022-10-17T15:23:22Z'
      message: ''
      observedGeneration: 2
      reason: Ready
      status: 'True'
      type: Ready
  expirationDate: '2023-01-15T14:23:20Z'
  issuerRef:
    cluster: target
    name: letsencrypt
    namespace: dev
  message: >-
    certificate (SN 4a:02:34:a0:c8:88:78:5b:cd:bf:01:40:12:f3:ad:ba:62:5) valid
    from 2022-10-17 14:23:21 +0000 UTC to 2023-01-15 14:23:20 +0000 UTC
  observedGeneration: 2
  state: Ready
  