apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: dev
  labels:
    app.kubernetes.io/name: letsencrypt
spec:
  requestsPerDayQuota: 0
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    email: andrew.lunde@sap.com
    autoRegistration: true
    domains:
      include:
        - cryptoassetssubledger.com
        - '*.cryptoassetssubledger.com'
    privateKeySecretRef:
      name: letsencrypt-xgm75
      namespace: dev