kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: crypto-rates-service-data
  labels:
    app: crypto-rates-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi