#!/bin/bash

FILE='
some:
  fields: "value"

images:
  image_1:
    name: "some-name"
    value: 1111
  image_2:
    name: "some-name-2"
    value: 1112
  image_3:
    name: "some-name-3"
    value: 1113

some:
  other-fields: "other-value"
'

echo adding new image to yaml - version 1
yq --argjson imageNo 4 --arg name "my_name" --argjson value 1114 '
  .images += { 
               "image_\($imageNo)":
               { 
                 name: $name,
                 value: $value
               }
             }' <<< "$FILE"

echo adding new image to yaml - version 2
yq --arg name "my_name" --argjson value 1114 '
  (.images | keys | length + 1) as $imageNo
  | .images += { 
                 "image_\($imageNo)":
                   { 
                     name: $name,
                     value: $value
                   }
               }' <<< "$FILE"
