apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ .Values.services.modx.name }}
spec:
  gateway: {{ .Values.gateway }}
  host: {{ .Values.services.modx.name }}.{{ .Values.clusterDomain }}
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - HEAD
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
  service:
    name: {{ .Values.services.modx.name }}
    port: {{ .Values.services.modx.service.port }}