version: "3"

services:
  wordpress:
    image: wordpress:5.7-php7.4
    restart: unless-stopped
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Nirvana8484
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: Nirvana8484
      MYSQL_RANDOM_ROOT_PASSWORD: "9"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  wordpress:
  mysql: