dockerID: alunde
providerSubdomain: cryptorates
clusterDomain: cryptoassetssubledger.com
gateway: crypto-assets-subledger-aws-gateway.dev.svc.cluster.local
services:
  app:
    name: crypto-rates-app
    image:
      repository: crypto-rates-app
      tag: "latest"
      pullPolicy: Always
      port: 5000
    service:
      port: 5000
  srv:
    name: crypto-rates-srv
    service:
      port: 5001
  sqlite:
    name: crypto-rates-sqlite
    image:
      repository: crypto-rates-sqlite
      tag: "latest"
      pullPolicy: Always
      port: 5003
    service:
      port: 5003
  uaa:
    name: crypto-rates-uaa
    bindingName: crypto-rates-uaa-binding
    bindingSecretName: crypto-rates-uaa-binding-secret
