apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ .Values.services.srvjs.name }}
spec:
  gateway: {{ .Values.gateway }}
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
  service:
    host: {{ .Values.services.srvjs.name }}.{{ .Values.clusterDomain }}

    name: {{ .Values.services.srvjs.name }}
    port: {{ .Values.services.srvjs.service.port }}