dockerID: alunde
clusterDomain: cryptoassetssubledger.com
gateway: crypto-assets-subledger-aws-gateway.dev.svc.cluster.local
services:
  app:
    name: crypto-rates-app
    image:
      repository: crypto-rates-app
      tag: "latest"
      pullPolicy: Always
      imagePullSecretName: docker-config
      port: 5000
    service:
      port: 5000
  srv:
    name: crypto-rates-srv
    service:
      port: 5001
  uaa:
    name: crypto-rates-uaa
    bindingName: crypto-rates-uaa-binding
    bindingSecretName: crypto-rates-uaa-binding-secret