apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.srv.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ .Values.services.srv.name }}
spec:
  ports:
    - port: {{ .Values.services.srv.service.port }}
      targetPort: {{ .Values.services.srv.image.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.services.srv.name }}