apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.app.name }}
data:
  TENANT_HOST_PATTERN: "^(.*)-{{ .Values.services.app.name }}.{{ .Values.clusterDomain }}"
  destinations: |
    [
      {
        "name": "sqlite",
        "url": "http://{{ .Values.services.sqlite.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.sqlite.service.port }}",
        "forwardAuthToken": true
      },
      {
        "name": "srv",
        "url": "http://{{ .Values.services.srv.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.srv.service.port }}",
        "forwardAuthToken": true
      }
    ]
